version: "3.7"

services:
  keycloak:
    image: keycloak/keycloak:latest
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - "/etc/ssl/keycloak/:/etc/x509/https" # map certificates to container
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_URL}
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB: postgres
      KC_DB_USERNAME:  ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    depends_on:
      - db
    networks:
      - keycloak
    command:
      - start

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    volumes:
      - ${KEYCLOAK_DB_PATH}:/var/lib/postgresql/data
    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: keycloak-net
    driver: bridge

volumes:
  postgres_data:
